spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

pj:
 lps:
   a: a1
   b: b1
   c: c1